run:
  timeout: 5m
  modules-download-mode: vendor
  tests: true  
  skip-dirs:
    - build
    - db
    - deploy
    - docker
    - helm
    - test-int
  skip-files:
  - cmd/server/config.go
output:
  format: colored-line-number

issues:
  exclude:
    - Using the variable on range scope .* in function literal

linters:
  disable-all: true
  enable:
    - bodyclose    
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gocritic
    - goimports
    - gosec
    - gosimple
    - goconst
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - varcheck 
    - unconvert
    - unparam
    - whitespace
