// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortalInfobloxClient is the client API for PortalInfoblox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortalInfobloxClient interface {
	GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type portalInfobloxClient struct {
	cc grpc.ClientConnInterface
}

func NewPortalInfobloxClient(cc grpc.ClientConnInterface) PortalInfobloxClient {
	return &portalInfobloxClient{cc}
}

func (c *portalInfobloxClient) GetVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/portalinfoblox.PortalInfoblox/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortalInfobloxServer is the server API for PortalInfoblox service.
// All implementations should embed UnimplementedPortalInfobloxServer
// for forward compatibility
type PortalInfobloxServer interface {
	GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error)
}

// UnimplementedPortalInfobloxServer should be embedded to have forward compatible implementations.
type UnimplementedPortalInfobloxServer struct {
}

func (UnimplementedPortalInfobloxServer) GetVersion(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

// UnsafePortalInfobloxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortalInfobloxServer will
// result in compilation errors.
type UnsafePortalInfobloxServer interface {
	mustEmbedUnimplementedPortalInfobloxServer()
}

func RegisterPortalInfobloxServer(s grpc.ServiceRegistrar, srv PortalInfobloxServer) {
	s.RegisterService(&PortalInfoblox_ServiceDesc, srv)
}

func _PortalInfoblox_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalInfobloxServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portalinfoblox.PortalInfoblox/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalInfobloxServer).GetVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PortalInfoblox_ServiceDesc is the grpc.ServiceDesc for PortalInfoblox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortalInfoblox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portalinfoblox.PortalInfoblox",
	HandlerType: (*PortalInfobloxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _PortalInfoblox_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/smailic05/portal-infoblox/pkg/pb/service.proto",
}
